[build]
  publish = "dist"
  command = "node netlify-debug.js && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://lms-backend-production.up.railway.app"
  VITE_DEMO_MODE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
