[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist')
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Build environment variables
  NODE_ENV = "production"
  VITE_APP_NAME = "Mitra Garage"
  VITE_APP_VERSION = "1.0.0"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# API proxy (optional - if you want to proxy API calls)
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-url.railway.app/api/:splat"
#   status = 200
#   force = true

# Form handling (if you have contact forms)
# [[redirects]]
#   from = "/contact"
#   to = "/.netlify/functions/contact"
#   status = 200
